### ISSUE TITLE
what removed GeekTools  

### ISSUE THREAD

**Issue by ExtinctDrift19** [HuskyDG/huskydg.github.io#1]
support discontinued GeekTools

**Comment by HuskyDG** [comment]
The reason why I stopped:
1. They release VMOS Pro too often, seems like VMOS PRO is become more buggy every update rather than bug fixes.
2. Lack of support busybox, which is important part of every modding tool (Lucky Patcher, etc.. ) and my script. There are no Busybox which can working well in VMOS.
3. If i use command busybox ls /sdcard Busybox from Magisk or osm0sis, it will show all folder on my phone instead of virtual machine 😌😌😌
That's mean VMOS is not **FULLY SANDBOX**
